-- MySQL Script generated by MySQL Workbench
-- Thu May 13 23:57:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema skillbox
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema skillbox
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `skillbox` DEFAULT CHARACTER SET utf8 ;
USE `skillbox` ;

-- -----------------------------------------------------
-- Table `skillbox`.`teachers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skillbox`.`teachers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT '  \\n',
  `salary` INT UNSIGNED NULL DEFAULT NULL COMMENT '  ',
  `age` INT UNSIGNED NULL DEFAULT NULL COMMENT ' ',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `skillbox`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skillbox`.`courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(500) NULL DEFAULT NULL,
  `duration` INT UNSIGNED NULL DEFAULT NULL COMMENT '   ',
  `type` ENUM('DESIGN', 'PROGRAMMING', 'MARKETING', 'MANAGEMENT', 'BUSINESS') NOT NULL COMMENT ' :  /  /  / ',
  `description` VARCHAR(500) NULL DEFAULT NULL,
  `teacher_id` INT UNSIGNED NULL DEFAULT NULL COMMENT '  ,   ',
  `students_count` INT UNSIGNED NULL DEFAULT NULL COMMENT '   ',
  `price` INT UNSIGNED NULL DEFAULT NULL COMMENT '   ',
  `price_per_hour` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `teacher_idx` (`teacher_id` ASC) VISIBLE,
  CONSTRAINT `teacher`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `skillbox`.`teachers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `skillbox`.`purchaselist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skillbox`.`purchaselist` (
  `student_name` VARCHAR(500) NULL DEFAULT NULL,
  `course_name` VARCHAR(500) NULL DEFAULT NULL,
  `price` INT NULL DEFAULT NULL,
  `subscription_date` DATETIME NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `skillbox`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skillbox`.`students` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL COMMENT ' ',
  `age` INT UNSIGNED NULL DEFAULT NULL COMMENT ' ',
  `registration_date` DATETIME NOT NULL COMMENT ' ',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 101
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `skillbox`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `skillbox`.`subscriptions` (
  `student_id` INT UNSIGNED NOT NULL,
  `course_id` INT UNSIGNED NOT NULL,
  `subscription_date` DATETIME NOT NULL,
  UNIQUE INDEX `unq` (`student_id` ASC, `course_id` ASC) VISIBLE,
  INDEX `course_idx` (`course_id` ASC) VISIBLE,
  CONSTRAINT `course`
    FOREIGN KEY (`course_id`)
    REFERENCES `skillbox`.`courses` (`id`),
  CONSTRAINT `student`
    FOREIGN KEY (`student_id`)
    REFERENCES `skillbox`.`students` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
